export const word_bank = [
  {
    level: 0,
    speed: 1000,
    words: [ "avocado",
      "raspberry",
      "cherry",
      "koala",
      "snowboard",
      "moonlight",
      "chameleon",
      "popsicle",
      "lightning",
      "toucan",
      "parrot",
      "blueberry",
      "zebra",
      "thunderstorm",
      "bubble",
      "firefly",
      "sombrero",
      "bookshelf",
      "jellyfish",
      "pinecone",
      "pretzel",
      "microphone",
      "satellite",
      "suitcase",
      "telescope",
      "crocodile",
      "caramel",
      "moon",
      "volcano",
      "panda",
      "candle",
      "penguin",
      '감자탕' ]
    ,
    message: 'level 0 cleared! Are you ready for level 1? '
  },
  {
    level: 1,
    speed: 700,
    words: [ "piano",
      "fireworks",
      "forest",
      "popcorn",
      "bumblebee",
      "trampoline",
      "snowflake",
      "baguette",
      "tornado",
      "coffee",
      "seagull",
      "tiger",
      "snowman",
      "laptop",
      "backpack",
      "flamingo",
      "saxophone",
      "sunflower",
      "pineapple",
      "camera",
      "violin",
      "binoculars",
      "bicycle",
      "raincoat",
      "seashell",
      "helicopter",
      "diamond",
      "paintbrush",
      "butterfly",
      "compass",
      "hammock",
      "giraffe",
      "cloud",
      "turtle",
      "basketball",
      "banana",
      "mango",
      "dolphin",
      "frisbee",
      "lemon",
      "cheetah",
      "campfire",
      "starfish",
      "guitar",
      "squirrel",
      "ostrich",
      "chocolate",
      "mountain" ]
    ,
    message: 'level 1 cleared! Are you ready for level 2? '
  },
  {
    level: 2,
    speed: 500,
    words: [ "cactus",
      "fountain",
      "coconut",
      "watermelon",
      "hammer",
      "ocean",
      "rainbow",
      "galaxy",
      "castle",
      "cookie",
      "sandcastle",
      "cruise",
      "dragon",
      "seahorse",
      "bamboo",
      "waterfall",
      "lighthouse",
      "elephant",
      "kangaroo",
      "sailboat",
      "lavender",
      "abstemious",
      "acquiesce",
      "adjudicate",
      "adumbrate",
      "aesthetic",
      "affable",
      "aggrandize",
      "alacrity",
      "amalgamate",
      "ameliorate",
      "anachronistic",
      "anomie",
      "antipathy",
      "apocryphal",
      "approbation",
      "arrogate",
      "ascetic",
      "assiduous",
      "atavistic",
      "austere",
      "avarice",
      "banal",
      "bellicose",
      "blandishment",
      "boorish",
      "bucolic",
      "cacophony",
      "cajole",
      "callow",
      "capricious",
      "castigate",
      "cathartic",
      "caustic",
      "chicanery",
      "choleric",
      "circumspect",
      "clandestine",
      "cloying",
      "coalesce",
      "complaisant",
      "concomitant",
      "conflagration",
      "confluence",
      "contentious",
      "contrite",
      "convivial",
      "corpulence",
      "coterie",
      "credulity",
      "cryptic",
      "cupidity",
      "dearth",
      "debacle",
      "decorum",
      "defenestration",
      "deleterious",
      "demagogue",
      "denouement",
      "derivative",
      "desuetude",
      "desultory",
      "diaphanous",
      "didactic",
      "diffident",
      "dilatory",
      "dilettante",
      "dirge",
      "disaffected",
      "discomfit",
      "disparate",
      "dissemble",
      "dissolute",
      "dissolution",
      "distrait",
      "dither",
      "dolorous",
      "doughty",
      "dowager",
      "dulcet",
      "ebullient",
      "edacious",
      "effete",
      "efficacy",
      "effrontery",
      "effulgent",
      "egregious",
      "elision",
      "emollient",
      "empyreal",
      "encomium",
      "endemic",
      "enervate" ],
    message: 'level 2 cleared! We got nothing for you!'
  }
]

type PosData = { row: number, col: number }

export const grid_pos: PosData[] = [
  { row: 1, col: 1 },
  { row: 1, col: 2 },
  { row: 1, col: 3 },
  { row: 2, col: 2 },
  { row: 2, col: 1 },
  { row: 2, col: 3 },
  { row: 3, col: 1 },
  { row: 3, col: 2 },
  { row: 3, col: 3 },
  { row: 4, col: 1 },
  { row: 4, col: 2 },
  { row: 4, col: 3 },
  { row: 5, col: 1 },
  { row: 5, col: 2 },
  { row: 5, col: 3 },
  { row: 6, col: 1 },
  { row: 6, col: 2 },
  { row: 6, col: 3 },
  { row: 7, col: 1 },
  { row: 7, col: 2 },
  { row: 7, col: 3 },
  { row: 8, col: 1 },
  { row: 8, col: 2 },
  { row: 8, col: 3 },
  { row: 9, col: 1 },
  { row: 9, col: 2 },
  { row: 9, col: 3 },
  { row: 10, col: 1 },
  { row: 10, col: 2 },
  { row: 10, col: 3 },
]