export const word_bank = [
  {

    level: 0,
    speed: 1000,
    words: [ "Avocado",
      "Raspberry",
      "Cherry",
      "Koala",
      "Snowboard",
      "Moonlight",
      "Chameleon",
      "Popsicle",
      "Lightning",
      "Toucan",
      "Parrot",
      "Blueberry",
      "Zebra",
      "Thunderstorm",
      "Bubble",
      "Firefly",
      "Sombrero",
      "Bookshelf",
      "Jellyfish",
      "Pinecone",
      "Pretzel",
      "Microphone",
      "Satellite",
      "Suitcase",
      "Telescope",
      "Crocodile",
      "Caramel",
      "Moon",
      "Volcano",
      "Panda",
      "Candle",
      "Penguin", ],
    message: 'level 0 cleared! Are you ready for level 1? '
  },
  {
    level: 1,
    speed: 700,
    words: [ "Piano",
      "Fireworks",
      "Forest",
      "Popcorn",
      "Bumblebee",
      "Trampoline",
      "Snowflake",
      "Baguette",
      "Tornado",
      "Coffee",
      "Seagull",
      "Tiger",
      "Snowman",
      "Laptop",
      "Backpack",
      "Flamingo",
      "Saxophone",
      "Sunflower",
      "Pineapple",
      "Camera",
      "Violin",
      "Binoculars",
      "Bicycle",
      "Raincoat",
      "Seashell",
      "Helicopter",
      "Diamond",
      "Paintbrush",
      "Butterfly",
      "Compass",
      "Hammock",
      "Giraffe",
      "Cloud",
      "Turtle",
      "Basketball",
      "Banana",
      "Mango",
      "Dolphin",
      "Frisbee",
      "Lemon",
      "Cheetah",
      "Campfire",
      "Starfish",
      "Guitar",
      "Squirrel",
      "Ostrich",
      "Chocolate",
      "Mountain", ],
    message: 'level 1 cleared! Are you ready for level 2? '
  },
  {
    level: 2,
    speed: 500,
    words: [ "Cactus",
      "Fountain",
      "Coconut",
      "Watermelon",
      "Hammer",
      "Ocean",
      "Rainbow",
      "Galaxy",
      "Castle",
      "Cookie",
      "Sandcastle",
      "Cruise",
      "Dragon",
      "Seahorse",
      "Bamboo",
      "Waterfall",
      "Lighthouse",
      "Elephant",
      "Kangaroo",
      "Sailboat",
      "Lavender",
      "abstemious",
      "acquiesce",
      "adjudicate",
      "adumbrate",
      "aesthetic",
      "affable",
      "aggrandize",
      "alacrity",
      "amalgamate",
      "ameliorate",
      "anachronistic",
      "anomie",
      "antipathy",
      "apocryphal",
      "approbation",
      "arrogate",
      "ascetic",
      "assiduous",
      "atavistic",
      "austere",
      "avarice",
      "banal",
      "bellicose",
      "blandishment",
      "boorish",
      "bucolic",
      "cacophony",
      "cajole",
      "callow",
      "capricious",
      "castigate",
      "cathartic",
      "caustic",
      "chicanery",
      "choleric",
      "circumspect",
      "clandestine",
      "cloying",
      "coalesce",
      "complaisant",
      "concomitant",
      "conflagration",
      "confluence",
      "contentious",
      "contrite",
      "convivial",
      "corpulence",
      "coterie",
      "credulity",
      "cryptic",
      "cupidity",
      "dearth",
      "debacle",
      "decorum",
      "defenestration",
      "deleterious",
      "demagogue",
      "denouement",
      "derivative",
      "desuetude",
      "desultory",
      "diaphanous",
      "didactic",
      "diffident",
      "dilatory",
      "dilettante",
      "dirge",
      "disaffected",
      "discomfit",
      "disparate",
      "dissemble",
      "dissolute",
      "dissolution",
      "distrait",
      "dither",
      "dolorous",
      "doughty",
      "dowager",
      "dulcet",
      "ebullient",
      "edacious",
      "effete",
      "efficacy",
      "effrontery",
      "effulgent",
      "egregious",
      "elision",
      "emollient",
      "empyreal",
      "encomium",
      "endemic",
      "enervate" ],
    message: 'level 2 cleared! We got nothing for you!'
  }
]

type PosData = { row: number, col: number }

export const grid_pos: PosData[] = [
  { row: 1, col: 1 },
  { row: 1, col: 2 },
  { row: 1, col: 3 },
  { row: 2, col: 2 },
  { row: 2, col: 1 },
  { row: 2, col: 3 },
  { row: 3, col: 1 },
  { row: 3, col: 2 },
  { row: 3, col: 3 },
  { row: 4, col: 1 },
  { row: 4, col: 2 },
  { row: 4, col: 3 },
  { row: 5, col: 1 },
  { row: 5, col: 2 },
  { row: 5, col: 3 },
  { row: 6, col: 1 },
  { row: 6, col: 2 },
  { row: 6, col: 3 },
  { row: 7, col: 1 },
  { row: 7, col: 2 },
  { row: 7, col: 3 },
  { row: 8, col: 1 },
  { row: 8, col: 2 },
  { row: 8, col: 3 },
]